spring:
  datasource:
    url: jdbc:mysql://${MINIO_HOST:localhost}:${MYSQL_PORT:3307}/clients
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:adminadmin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8090

service:
  names:
    - asdada
    - asdadada

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org.springframework.security: TRACE

